"""followers

Revision ID: 21697e6e2ba0
Revises: 06a80e596a29
Create Date: 2022-09-07 12:45:59.389716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21697e6e2ba0'
down_revision = '06a80e596a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
